class DominosTester{
	public static void dominostest() {
		double priceOfFood;
                System.out.println("\nFirst Call\n");
		String food="Cheese Pizza";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Margherita Pizza";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Margherita Pizza Medium";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Margherita Pizza Large";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="SpicyTriple Tango Regular";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="SpicyTriple Tango Medium";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="SpicyTriple Tango Large";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Cheese Pizza";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Peppy Paneer";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Veg Pizza";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Chicken Pizza";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Extravaganza Pizza";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Veg Wonder";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="5 Pepper";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Chicken Non Veg Pizza";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Chicken Farmhouse Regular";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Pepperoni Pizza";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Momos Pizza";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Deluxe Veggie";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Zesty Chicken";
		priceOfFood=Dominos.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
//overload call
System.out.println("\nOver laod call\n");

        food="Cheese Pizza";
        priceOfFood=Dominos.search(food,2);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Margherita Pizza";
        priceOfFood=Dominos.search(food,3);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Margherita Pizza Medium";
        priceOfFood=Dominos.search(food,4);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Margherita Pizza Large";
        priceOfFood=Dominos.search(food,8);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="SpicyTriple Tango Regular";
        priceOfFood=Dominos.search(food,6);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="SpicyTriple Tango Medium";
        priceOfFood=Dominos.search(food,2);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="SpicyTriple Tango Large";
        priceOfFood=Dominos.search(food,4);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Cheese Pizza";
        priceOfFood=Dominos.search(food,4);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Peppy Paneer";
        priceOfFood=Dominos.search(food,8);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Veg Pizza";
        priceOfFood=Dominos.search(food,1);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Chicken Pizza";
        priceOfFood=Dominos.search(food,3);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Extravaganza Pizza";
        priceOfFood=Dominos.search(food,2);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Veg Wonder";
        priceOfFood=Dominos.search(food,3);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="5 Pepper";
        priceOfFood=Dominos.search(food,4);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Chicken Non Veg Pizza";
        priceOfFood=Dominos.search(food,10);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Chicken Farmhouse Regular";
        priceOfFood=Dominos.search(food,2);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Pepperoni Pizza";
        priceOfFood=Dominos.search(food,9);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Momos Pizza";
        priceOfFood=Dominos.search(food,3);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Deluxe Veggie";
        priceOfFood=Dominos.search(food,1);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Zesty Chicken";
        priceOfFood=Dominos.search(food,2);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        
	}
}