class McDonaldsTester{
	public static void mcdonaldstest() {
		System.out.println("\nThe first call\n");
        double priceOfFood;
		String food="Mc Aloo Tikki";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Pizza Puff";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Mc Aloo Tikki Meal";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Big Mac Meal";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Coke Float";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Peri Peri French Fries";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Spicy Big Mac";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Fanta FLoat";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Softie";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Happy Meal";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Chicken McGrill";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Mc Egg";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Aloo Wrap";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Veg Wrap";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Egg Wrap";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Big Spicy Chicken Wrap";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Big Spicy Paneer Wrap";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Chicken McNuggets";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Mc Flurry Oreo";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Ice Tea";
		priceOfFood=McDonalds.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        
System.out.println("\nOverload Call\n");
        
        food="Mc Aloo Tikki";
        priceOfFood=McDonalds.search(food,4);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Pizza Puff";
        priceOfFood=McDonalds.search(food,3);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Mc Aloo Tikki Meal";
        priceOfFood=McDonalds.search(food,2);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Big Mac Meal";
        priceOfFood=McDonalds.search(food,3);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Coke Float";
        priceOfFood=McDonalds.search(food,4);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Peri Peri French Fries";
        priceOfFood=McDonalds.search(food,4);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Spicy Big Mac";
        priceOfFood=McDonalds.search(food,6);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Fanta FLoat";
        priceOfFood=McDonalds.search(food,7);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Softie";
        priceOfFood=McDonalds.search(food,10);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Happy Meal";
        priceOfFood=McDonalds.search(food,7);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Chicken McGrill";
        priceOfFood=McDonalds.search(food,3);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Mc Egg";
        priceOfFood=McDonalds.search(food,7);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Aloo Wrap";
        priceOfFood=McDonalds.search(food,3);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Veg Wrap";
        priceOfFood=McDonalds.search(food,6);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Egg Wrap";
        priceOfFood=McDonalds.search(food,3);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Big Spicy Chicken Wrap";
        priceOfFood=McDonalds.search(food,7);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Big Spicy Paneer Wrap";
        priceOfFood=McDonalds.search(food,3);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Chicken McNuggets";
        priceOfFood=McDonalds.search(food,7);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Mc Flurry Oreo";
        priceOfFood=McDonalds.search(food,6);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Ice Tea";
        priceOfFood=McDonalds.search(food,5);
        System.out.println("The Price of "+food+" is "+priceOfFood);
	}
}