class UberEatsTester{
		public static void uberTest() {
		double priceOfFood;
        System.out.println("\nnormal call\n");
		String food="Burrito";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Salted French Fries";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Cheeseburger";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Chicken Sandwich";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Breakfast Sandwich";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Soup";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Pancakes";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Sausage";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Mozarella Pizza";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Steak";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Wings";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Beer";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Salad";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="American Cheese";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Sour Cream";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Bread";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Ham";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Hot Cheetos";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Sushi";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Watermelon";
		priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
//overload call
        System.out.println("\nOverload Call\n");
        food="Burrito";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Salted French Fries";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Cheeseburger";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Chicken Sandwich";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Breakfast Sandwich";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Soup";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Pancakes";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Sausage";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Mozarella Pizza";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Steak";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Wings";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Beer";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Salad";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="American Cheese";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Sour Cream";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Bread";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Ham";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Hot Cheetos";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);
        food="Sushi";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+ "is "+priceOfFood);
        food="Watermelon";
        priceOfFood=UberEats.search(food);
        System.out.println("The Price of "+food+" is "+priceOfFood);




	}
}