class BooksTester {
    public static void main(String[] args) {
        Books b1 = new Books();
        b1.bookAuthor = "Chethan bhagat";
        b1.bookName = "400 days";
        b1.bookType = "Fiction";
        b1.publicationName = "westland publications";
        b1.price = 125;
        b1.noOfPages = 352;
        System.out.println("Book : ");
        System.out.println("Name : " + b1.bookName);
        System.out.println("Author : " + b1.bookAuthor);
        System.out.println("Genre : " + b1.bookType);
        System.out.println("Publication : " + b1.publicationName);
        System.out.println("Pages : " + b1.noOfPages);
        System.out.println("Price : " + b1.price);
        b1.gainKnowledge();

        Books b2 = new Books();
        b2.bookAuthor = "Bond Ruskin";
        b2.bookName = "The blue umbrella ";
        b2.bookType = "Fiction";
        b2.publicationName = "rupa & co";
        b2.price = 148;
        b2.noOfPages = 64;
        System.out.println("Book : ");
        System.out.println("Name : " + b2.bookName);
        System.out.println("Author : " + b2.bookAuthor);
        System.out.println("Genre : " + b2.bookType);
        System.out.println("Publication : " + b2.publicationName);
        System.out.println("Pages : " + b2.noOfPages);
        System.out.println("Price : " + b2.price);
        b2.gainKnowledge();

        Books b3 = new Books();
        b3.bookAuthor = "Chethan bhagat";
        b3.bookName = "one indian girl";
        b3.bookType = "Fiction";
        b3.publicationName = "rupa & co";
        b3.price = 148;
        b3.noOfPages = 280;
        System.out.println("Book : ");
        System.out.println("Name : " + b3.bookName);
        System.out.println("Author : " + b3.bookAuthor);
        System.out.println("Genre : " + b3.bookType);
        System.out.println("Publication : " + b3.publicationName);
        System.out.println("Pages : " + b3.noOfPages);
        System.out.println("Price : " + b3.price);
        b3.gainKnowledge();

        Books b4 = new Books();
        b4.bookAuthor = "jane austen";
        b4.bookName = "pride and prejudice";
        b4.bookType = "classics";
        b4.publicationName = "vayu education";
        b4.price = 150;
        b4.noOfPages = 328;
        System.out.println("Book : ");
        System.out.println("Name : " + b4.bookName);
        System.out.println("Author : " + b4.bookAuthor);
        System.out.println("Genre : " + b4.bookType);
        System.out.println("Publication : " + b4.publicationName);
        System.out.println("Pages : " + b4.noOfPages);
        System.out.println("Price : " + b4.price);
        b4.gainKnowledge();

        Books b5 = new Books();
        b5.bookAuthor = "bond ruskin";
        b5.bookName = "falling in love again";
        b5.bookType = "Fiction";
        b5.publicationName = "rupa & co";
        b5.price = 233;
        b5.noOfPages = 208;
        System.out.println("Book : ");
        System.out.println("Name : " + b5.bookName);
        System.out.println("Author : " + b5.bookAuthor);
        System.out.println("Genre : " + b5.bookType);
        System.out.println("Publication : " + b5.publicationName);
        System.out.println("Pages : " + b5.noOfPages);
        System.out.println("Price : " + b5.price);
        b5.gainKnowledge();

        Books b6 = new Books();
        b6.bookAuthor = "o brien terry";
        b6.bookName = "50 greatest short stories";
        b6.bookType = "Fiction";
        b6.publicationName = "rupa & co";
        b6.price = 263;
        b6.noOfPages = 588;
        System.out.println("Book : ");
        System.out.println("Name : " + b6.bookName);
        System.out.println("Author : " + b6.bookAuthor);
        System.out.println("Genre : " + b6.bookType);
        System.out.println("Publication : " + b6.publicationName);
        System.out.println("Pages : " + b6.noOfPages);
        System.out.println("Price : " + b6.price);
        b6.gainKnowledge();

        Books b7 = new Books();
        b7.bookAuthor = "swift jonathan";
        b7.bookName = "gullivers travels";
        b7.bookType = "Fiction";
        b7.publicationName = "prakash books";
        b7.price = 128;
        b7.noOfPages = 312;
        System.out.println("Book : ");
        System.out.println("Name : " + b7.bookName);
        System.out.println("Author : " + b7.bookAuthor);
        System.out.println("Genre : " + b7.bookType);
        System.out.println("Publication : " + b7.publicationName);
        System.out.println("Pages : " + b7.noOfPages);
        System.out.println("Price : " + b7.price);
        b7.gainKnowledge();

        Books b8 = new Books();
        b8.bookAuthor = "sanjay choubey";
        b8.bookName = "9th november";
        b8.bookType = "novel";
        b8.publicationName = "connoisseur";
        b8.price = 154;
        b8.noOfPages = 243;
        System.out.println("Book : ");
        System.out.println("Name : " + b8.bookName);
        System.out.println("Author : " + b8.bookAuthor);
        System.out.println("Genre : " + b8.bookType);
        System.out.println("Publication : " + b8.publicationName);
        System.out.println("Pages : " + b8.noOfPages);
        System.out.println("Price : " + b8.price);
        b8.gainKnowledge();

        Books b9 = new Books();
        b9.bookAuthor = "verne jules";
        b9.bookName = "journey to the centre of the earth";
        b9.bookType = "Fiction";
        b9.publicationName = "westland publications";
        b9.price = 111;
        b9.noOfPages = 240;
        System.out.println("Book : ");
        System.out.println("Name : " + b9.bookName);
        System.out.println("Author : " + b9.bookAuthor);
        System.out.println("Genre : " + b9.bookType);
        System.out.println("Publication : " + b9.publicationName);
        System.out.println("Pages : " + b9.noOfPages);
        System.out.println("Price : " + b9.price);
        b9.gainKnowledge();

        Books b10 = new Books();
        b10.bookAuthor = "machiavelli niccolo";
        b10.bookName = "the prince";
        b10.bookType = "Fiction";
        b10.publicationName = "prakash books";
        b10.price = 96;
        b10.noOfPages = 184;
        System.out.println("Book : ");
        System.out.println("Name : " + b10.bookName);
        System.out.println("Author : " + b10.bookAuthor);
        System.out.println("Genre : " + b10.bookType);
        System.out.println("Publication : " + b10.publicationName);
        System.out.println("Pages : " + b10.noOfPages);
        System.out.println("Price : " + b10.price);
        b10.gainKnowledge();
    }
}
