class ToysTester {
    public static void main(String[] args) {
        Toys t1 = new Toys();
        t1.brandName = "Tractor";
        t1.toyType = "Hard Toy";
        t1.size = "Small";
        t1.price = 250;
        System.out.println("Toys : ");
        System.out.println("Brand : " + t1.brandName );
        System.out.println("Type : " + t1.toyType );
        System.out.println("Size : " + t1.size );
        System.out.println("Price : " + t1.price );
        t1.play();

        Toys t2 = new Toys();
        t2.brandName = "Panda";
        t2.toyType = "Soft Toy";
        t2.size = "Big";
        t2.price = 2000;
        System.out.println("Toys : ");
        System.out.println("Brand : " + t2.brandName );
        System.out.println("Type : " + t2.toyType );
        System.out.println("Size : " + t2.size );
        System.out.println("Price : " + t2.price );
        t2.play();
		
		Toys t1 = new Toys();
        t3.brandName = "Car";
        t3.toyType = "Hard Toy";
        t3.size = "Medium";
        t3.price = 600;
        System.out.println("Toys : ");
        System.out.println("Brand : " + t3.brandName );
        System.out.println("Type : " + t3.toyType );
        System.out.println("Size : " + t3.size );
        System.out.println("Price : " + t3.price );
        t3.play();
		
		Toys t4 = new Toys();
        t4.brandName = "car";
        t4.toyType = "Remote Control";
        t4.size = "Medium";
        t4.price = 5000;
        System.out.println("Toys : ");
        System.out.println("Brand : " + t4.brandName );
        System.out.println("Type : " + t4.toyType );
        System.out.println("Size : " + t4.size );
        System.out.println("Price : " + t4.price );
        t4.play();
		
		Toys t5 = new Toys();
        t5.brandName = "Lion";
        t5.toyType = "soft Toy";
        t5.size = "Small";
        t5.price = 599;
        System.out.println("Toys : ");
        System.out.println("Brand : " + t5.brandName );
        System.out.println("Type : " + t5.toyType );
        System.out.println("Size : " + t5.size );
        System.out.println("Price : " + t5.price );
        t5.play();
		
		Toys t6 = new Toys();
        t6.brandName = "Ben 10 Watch";
        t6.toyType = "Hard Toy";
        t6.size = "Medium";
        t6.price = 500;
        System.out.println("Toys : ");
        System.out.println("Brand : " + t6.brandName );
        System.out.println("Type : " + t6.toyType );
        System.out.println("Size : " + t6.size );
        System.out.println("Price : " + t6.price );
        t6.play();
		
		Toys t7 = new Toys();
        t7.brandName = "Tractor";
        t7.toyType = "Hard Toy";
        t7.size = "Small";
        t7.price = 250;
        System.out.println("Toys : ");
        System.out.println("Brand : " + t7.brandName );
        System.out.println("Type : " + t7.toyType );
        System.out.println("Size : " + t7.size );
        System.out.println("Price : " + t7.price );
        t7.play();
		
		Toys t8 = new Toys();
        t8.brandName = "Lego";
        t8.toyType = "Hard Toy";
        t8.size = "Big";
        t8.price = 2500;
        System.out.println("Toys : ");
        System.out.println("Brand : " + t8.brandName );
        System.out.println("Type : " + t8.toyType );
        System.out.println("Size : " + t8.size );
        System.out.println("Price : " + t8.price );
        t8.play();
		
		Toys t9 = new Toys();
        t9.brandName = "Bike";
        t9.toyType = "Hard Toy";
        t9.size = "Small";
        t9.price = 400;
        System.out.println("Toys : ");
        System.out.println("Brand : " + t9.brandName );
        System.out.println("Type : " + t9.toyType );
        System.out.println("Size : " + t9.size );
        System.out.println("Price : " + t9.price );
        t9.play();
		
		 Toys t10 = new Toys();
        t10.brandName = "Zebra";
        t10.toyType = "Soft Toy";
        t10.size = "Small";
        t10.price = 750;
        System.out.println("Toys : ");
        System.out.println("Brand : " + t10.brandName );
        System.out.println("Type : " + t10.toyType );
        System.out.println("Size : " + t10.size );
        System.out.println("Price : " + t10.price );
        t10.play();